### ISSUE TITLE
Data-Structures-and-Algorithm-Analysis-in-C/ch04/AvlTree.cpp

### ISSUE THREAD

**Issue by xiaoshudi** [seineo/Data-Structures-and-Algorithm-Analysis-in-C#1]
![image](https://user-images.githubusercontent.com/38290717/85974370-e0f65980-ba07-11ea-9881-d5ee5e2f6424.png)
The judgment in the red box seems unnecessary！

**Comment by seineo** [comment]
Sorry, I just saw your issue. 
Yes, you're totally right. But I think it's a good habit to check whether the root is null pointer at first, so I decide to left it there.
Thanks for your issue and feel free to submit more!
